[package]
name = "majorization"
version = "0.1.0"
authors = ["alex gucci <alexgusain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


serde_json = "*"

rand = "0.8.4"

plotters = "*"