steps:
  #copy the prediction and 
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'gs://mtg-ml/PREDICTION', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/cheaper-324003/deckassistant:latest', '-f', './deckassistant/Dockerfile',  '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cheaper-324003/deckassistant:latest']